language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - mysql trackway < absenceReasons.sql
  - mysql trackway < groups.sql

script:
  - phpunit -c app/
