fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fosgroup:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

app:
    resource: @AppBundle/Controller/
    type:     annotation
