security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|fonts|images|js)/
            security: false

    access_control:
        - { path: ^(/[a-z]+)?/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/[a-z]+)?/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/[a-z]+)?/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/[a-z]+)?/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }