services:
    app.registration.form.type:
        class:      AppBundle\Form\Type\ProfileFormType
        arguments:  [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: appbundle_profile }

    security.access.basetimeentry_voter:
        class:      AppBundle\Security\Authorization\Voter\BaseTimeEntryVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.membership_voter:
        class:      AppBundle\Security\Authorization\Voter\MembershipVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.project_voter:
        class:      AppBundle\Security\Authorization\Voter\ProjectVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.task_voter:
        class:      AppBundle\Security\Authorization\Voter\TaskVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.team_voter:
        class:      AppBundle\Security\Authorization\Voter\TeamVoter
        public:     false
        tags:
           - { name: security.voter }