---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: trackway.vagrant 192.168.33.99
    timezone: Europe/Berlin

  vars_files:
    - vars/main.yml

  roles:
    - { role: init, tags: init }
    - { role: php5-cli, tags: php5-cli }
    - { role: apache, tags: apache }
    - { role: php5, tags: php5 }
    - { role: mariadb, tags: mariadb }
    - { role: nodejs, tags: nodejs }
    - { role: app, tags: app }